[main]
prompt="$"
dpi-aware=yes
icons=yes
width=40
terminal=alacritty -a '{cmd}' -T '{cmd}' {cmd}
lines=20
horizontal-pad=8
font = monospace:size=10
anchor = top
y-margin= 10

[colors]
background=1E1E1Eff
text=E0E0E0ff
match=DC6666ff
selection=DC6666ff
selection-text=1E1E1Eff
border=DC6666ff

[border]
width=2
radius=8

#https://man.archlinux.org/man/fuzzel.ini.5.en
