general {
    disable_loading_bar = true
    hide_cursor = true
}

label {
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(E0E0E0ff)
    font_size = 64
    font_family = monospace

    position = 0, 80
    halign = center
    valign = center
}

label {
    text = cmd[update:10000] echo "$(date +'%A, %d %B %Y')"
    color = rgba(E0E0E0aa)
    font_size = 18
    font_family = monospace

    position = 0, 30
    halign = center
    valign = center
}

input-field {
    size = 20%, 5%
    outline_thickness = 2.5

    dots_size = 0.3
    dots_spacing = 0.2
    dots_center = true

    outer_color = rgba(DC6666ff)
    inner_color = rgba(1E1E1Eff) 
    font_color = rgba(E0E0E0ff)

    fade_on_empty = false

    position = 0, -80
    halign = center
    valign = center
}

background {
    path = screenshot
    blur_passes = 2
 
